# Generated by Django 4.0.3 on 2022-03-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='Qualification',
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
