# Generated by Django 4.0.5 on 2022-06-10 07:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('product', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('customer_image', models.ImageField(upload_to='')),
                ('customer_file', models.FileField(upload_to='')),
            ],
        ),
    ]
