# Generated by Django 4.0.4 on 2022-05-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='menu',
            new_name='medicine',
        ),
    ]
