# Generated by Django 4.0.4 on 2022-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cbill',
            field=models.FloatField(),
        ),
    ]
